service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2:
    use_v2: true
    http:
      endpoint: "0.0.0.0:13133"
  jaeger_query:
    storage:
      traces: storage
      metrics: storage
  jaeger_storage:
    backends:
      storage:
        elasticsearch:
          server_urls:
            - http://elastic:9200
    metric_backends:
      storage:
        elasticsearch:
          server_urls:
            - http://elastic:9200

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: storage
