services:
  store:
    url: ${STORE_URL:http://store:8180}
    pattern: /store/api/public/**
  warehouse:
    url: ${WAREHOUSE_URL:http://warehouse:8280}
    pattern: /warehouse/api/public/**
  warranty:
    url: ${WARRANTY_URL:http://warranty:8380}
    pattern: /warranty/api/public/**

management:
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces

logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}]"
