services:
  warehouse-url: ${WAREHOUSE_URL:http://warehouse:8280}
  warranty-url: ${WARRANTY_URL:http://warranty:8380}

management:
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces

logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}]"
