services:
  store:
    url: http://localhost:8180
    pattern: /store/api/public/**
  warehouse:
    url: http://localhost:8280
    pattern: /warehouse/api/public/**
  warranty:
    url: http://localhost:8380
    pattern: /warranty/api/public/**

management:
  tracing:
    enabled: false
