server:
  port: ${APPLICATION_PORT:8380}
  forward-headers-strategy: framework
  servlet:
    context-path: ${APPLICATION_CONTEXT_PATH:/}

spring:
  profiles:
    active: local
    include: common
  config:
    import: optional:git.properties
  application:
    name: warranty
