spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warranty
    username: program
    password: test
    driver-class-name: org.postgresql.Driver

services:
  warehouse-url: ${WAREHOUSE_URL:http://localhost:8280}

oauth2:
  security:
    enabled: false

management:
  tracing:
    enabled: false
