global:
  scrape_interval: 5s
  external_labels:
    monitor: "services-monitor"

scrape_configs:
  - job_name: "services"
    metrics_path: "/manage/prometheus"
    static_configs:
      - targets:
          - "gateway:8080"
          - "orders:8180"
          - "warehouse:8280"
          - "warranty:8380"

  - job_name: cadvisor
    static_configs:
      - targets: [ "cadvisor:8080" ]

  - job_name: node-exporter
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: postgres-exporter
    metrics_path: /metrics
    static_configs:
      - targets: [ "postgres-exporter:9187" ]

  - job_name: trace-metrics
    static_configs:
      - targets: [ "jaeger:8889" ]
