profile: k8s,auth0

ingress:
  enabled: true
  domain: local

database:
  host: postgres
  port: 5432
  username: program
  password: test

environments:
  - name: OAUTH2_SECURITY_ENABLED
    value: true

resources:
  requests:
    cpu: 0.5
    memory: 1024Mi
  limits:
    cpu: 0.5
    memory: 1024Mi

circuitBreaker:
  enabled: false

tracing:
  enabled: false
  host: fluent-bit
  port: 6831

logging:
  enabled: false
  host: jaeger
  port: 6831
